### ISSUE TITLE
It's weird to create account with email address

### ISSUE THREAD

**Issue by elsehow** [CommonGarden/Grow-IoT#136]
why does my local server want my email address? some sort of username/password would make me feel more comfortable
- [x] Sign up using username instead of email
- [x] Switch out owner property for username or userapikey

**Comment by JakeHartnell** [comment]
Cool, I think I'm going to kill this "feature" for now... 

The problem is, this project is missing an important chunk: UI to configure devices from the App. We could easily generate an API key instead of an Email address, but it's still only going to be a project for developers until we can configure devices from the app.

I'll open a separate issue for this somewhere / sometime, but yes, I agree with you. It is weird, let's kill it.
