### ISSUE TITLE
User Not Found When using Email for Login

### ISSUE THREAD

**Issue by cloudzombie** [CommonGarden/Grow-IoT#157]
When creating the first and only existing user with email address, it logs in fine, but once you logout, the user cannot be found, but cannot be created because already exists.

**Comment by JakeHartnell** [comment]
Hmmm... I recently changed it so it just requires a username. Until I get a chance to look closer, if you try creating another account with just a username like 'test', logout, and then try to login again does it work?

**Comment by JakeHartnell** [comment]
> When creating the first and only existing user with email address, it logs in fine, but once you logout, the user cannot be found, but cannot be created because already exists. 

Yeah, this is a bug.

**Comment by JakeHartnell** [comment]
Ok, looked into this a bit more. We need to perhaps open up a larger 'support email' issue which will include things like making sure password reset works correctly.

As a quick fix for this particular issue, we might provide a validation warning if someone tries to create an account with an Email address? @cloudzombie do you have a preference for this. Is email support something you need sooner rather than later?

**Comment by JakeHartnell** [comment]
https://github.com/CommonGarden/Grow-IoT/pull/176 will hopefully make things a bit better.

**Comment by JakeHartnell** [comment]
Hopefully addressed with #176, let me know if any problems persist.
